# -*- coding: utf-8 -*-
"""ProjectAssignment6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iO6EXR7KFzWSdGBe1VsPPY_wCml4YhY3
"""

from pyspark.sql import SparkSession

# Block lines to run locally
import os
BASE = os.path.abspath(".")
WAREHOUSE_URI=f"file:{BASE}/warehouse"

spark = (SparkSession.builder
         .appName("CS131 - WeTheBestMusic Final")
         .config("spark.sql.shuffle.partitions", "8")
        #  .master("local[*]")
        #  .config("spark.sql.warehouse.dir", WAREHOUSE_URI)
         .getOrCreate())

spark

# Block to run locally
# !curl -L -o ./ultimate-spotify-tracks-db.zip \
# https://www.kaggle.com/api/v1/datasets/download/zaheenhamidani/ultimate-spotify-tracks-db
# !unzip ultimate-spotify-tracks-db.zip
# !ls
# dataset = "/content/SpotifyFeatures.csv"
# OUT_PATH = "out"

bucket="wtbm-spotify"
dataset = f"gs://{bucket}/data/SpotifyFeatures.csv"
OUT_PATH = f"gs://{bucket}/out"

from pyspark.sql import functions as F
df_raw = (spark.read
          .option("header", True)
          .option("inferSchema", True)
          .csv(dataset))

print("Raw rows:", df_raw.count())
df_raw.printSchema()
df_raw.show(5, truncate=False)

df = df_raw

# We treat track_id as the unique ID
PK_COL = "track_id"
POP_COL = "popularity"

# 1) Drop rows with missing track_id
df = df.filter(F.col(PK_COL).isNotNull())
print("Rows after step 1:", df.count())

# 2) Drop rows with invalid number of columns (caused by commas in track name)
df = df.filter(F.col(POP_COL).cast("int").isNotNull())
print("Rows after step 2:", df.count())

# 3) Fill missing artist/track names with "Unknown"
df = df.fillna({
    "artist_name": "Unknown",
    "track_name": "Unknown"
})
print("Rows after step 3:", df.count())

# 4) Remove exact duplicate rows
df = df.dropDuplicates(["track_id"])

print("Rows after cleaning:", df.count())
df.show(5, truncate=False)

genre_artist_df = df.select("genre", "artist_name", "track_name", "popularity",
  "tempo", "danceability", "duration_ms")
key_df = df.select("track_name", "key", "mode", "popularity", "loudness",
  "energy")

genre_statistics = genre_artist_df.groupBy("genre", "artist_name") \
  .agg(F.count("track_name").alias("number_of_tracks"),
       F.round(F.avg("popularity"), 3).alias("avg_popularity"),
       F.round(F.avg("tempo"), 3).alias("avg_bpm")) \
  .orderBy(F.desc("number_of_tracks"), F.desc("avg_popularity"))
genre_statistics.show()

artists_by_genre = genre_artist_df.groupBy("artist_name","genre") \
  .agg(F.count("track_name").alias("number_of_tracks"),
       F.round(F.avg("popularity"), 3).alias("avg_popularity"),
       F.round(F.avg("danceability"), 3).alias("avg_danceability"), \
       F.round(F.avg("duration_ms"), 3).alias("avg_length (ms)")) \
  .orderBy(F.desc("number_of_tracks"), F.desc("avg_popularity"))
artists_by_genre.show()


most_popular_signatures = key_df.groupBy("key", "mode") \
  .agg(F.count("track_name").alias("number_of_tracks"),
       F.round(F.avg("popularity"), 3).alias("avg_popularity"),
       F.round(F.avg("loudness"), 3).alias("avg_loudness"),
       F.round(F.avg("energy"), 3).alias("avg_energy")) \
  .orderBy("key", "mode")
most_popular_signatures.show()

"""## New Aggregations"""

reduced_df = df.select("artist_name", "time_signature", "track_name",
  "popularity", "energy", "tempo")

# Artist grouped by time signatures
artist_time_signatures = (reduced_df.groupBy("artist_name", "time_signature")
  .agg(F.count("track_name").alias("number_of_tracks"),
       F.round(F.avg("popularity"), 3).alias("avg_popularity"),
       F.round(F.avg("energy"), 3).alias("energy"),
       F.round(F.avg("tempo"), 3).alias("avg_bpm"))
  .orderBy(F.desc("avg_popularity")))
artist_time_signatures.show()

# Bucketization of energy
from pyspark.ml.feature import Bucketizer
splits = [-float("inf"), .33, .66, float("inf")] # Split into 3 buckets low medium high [0,.33) [.33,.66) [.66,1]
bucketizer = Bucketizer(splits=splits, inputCol="energy", outputCol="energy_buckets")

energy_buckets = (bucketizer.transform(artist_time_signatures)
  .select("artist_name","time_signature","avg_popularity","energy_buckets")
  .withColumn("energy_buckets",
      F.when(F.col("energy_buckets")==0, "low")
      .when(F.col("energy_buckets")==1, "medium")
      .when(F.col("energy_buckets")==2, "high")))

popular_energy_counts = (energy_buckets.filter(F.col("avg_popularity").between(50, 100))
  .groupBy("energy_buckets")
  .agg(F.count("energy_buckets").alias("count")))
# We can see that the majority of the songs are rarer in their time signature
# from a particular artist and fit in our medium to high energy buckets
energy_buckets.show()
popular_energy_counts.show()

"""## Time Comparisons for Coalescence"""

import time
t0 = time.time()
(energy_buckets
    .write.mode("overwrite")
    .option("header", True)
    .csv("energy_buckets"))
tdelta = time.time() - t0
print(f"Time for no coalesce write: {tdelta:.3f}s")

t0 = time.time()
(energy_buckets
    .coalesce(1)
    .write.mode("overwrite")
    .option("header", True)
    .csv("energy_buckets"))
tdelta = time.time() - t0
print(f"Time for coalesce write: {tdelta:.3f}s")

"""## Time Comparisons for Repartition"""

import time
 # Non-repartioned Saves
t0 = time.time()
(genre_statistics
  .write.mode("overwrite")
  .partitionBy("genre")
  .option("header", True)
  .csv(f"{OUT_PATH}/genre_stats"))

(energy_buckets
  .write.mode("overwrite")
  .partitionBy("energy_buckets")
  .option("header", True)
  .csv(f"{OUT_PATH}/energy_buckets"))

(most_popular_signatures
  .write.mode("overwrite")
  .partitionBy("key")
  .option("header", True)
  .csv(f"{OUT_PATH}/key_signatures"))
tdelta = time.time() - t0
print(f"Time for non-repartioned writes: {tdelta:.3f}s")

 # Repartitioned Saves
t0 = time.time()
(genre_statistics.repartition(8, "genre")
  .write.mode("overwrite")
  .partitionBy("genre")
  .option("header", True)
  .csv(f"{OUT_PATH}/genre_stats"))

(energy_buckets.repartition(8, "artist_name")
  .write.mode("overwrite")
  .partitionBy("energy_buckets")
  .option("header", True)
  .csv(f"{OUT_PATH}/energy_buckets"))

(most_popular_signatures.repartition(8, "key")
  .write.mode("overwrite")
  .partitionBy("key")
  .option("header", True)
  .csv(f"{OUT_PATH}/key_signatures"))
tdelta = time.time() - t0
print(f"Time for repartioned writes: {tdelta:.3f}s")

# ML Model:
from pyspark.sql import functions as F
from pyspark.ml.feature import Bucketizer
from pyspark.ml.feature import VectorAssembler
from pyspark.ml.stat import Correlation

numeric_cols = [
    "acousticness", "danceability", "duration_ms", "energy",
    "instrumentalness", "liveness", "loudness",
    "speechiness", "tempo", "popularity", "valence"
]
for c in numeric_cols:
    df = df.withColumn(c, F.col(c).cast("float"))

q1, q2 = df.approxQuantile("popularity", [1/3, 2/3], 0.01) # Get quntiles .33 and .66
splits = [-float("inf"), q1, q2, float("inf")] # Split into 3 buckets low medium high [0,.33) [.33,.66) [.66,1]
bucketizer = Bucketizer(splits=splits, inputCol="popularity", outputCol="popularity_class")
df_labeled = bucketizer.transform(df).withColumn("label", F.col("popularity_class").cast("int")).drop("popularity_class")
# Add the popularity classification to the df
df_labeled.printSchema()

stats = df_labeled.select(
    [F.mean(c).alias(f"{c}_mean") for c in numeric_cols] +
    [F.stddev(c).alias(f"{c}_std") for c in numeric_cols] +
    [(F.max(c) - F.min(c)).alias(f"{c}_range") for c in numeric_cols]
    )

stats.show(truncate=False)
# Create 3 serperate dataframes and add them together
# From this we can see there is no issues with ranges, means or stds for any of the numeric columns

assembler = VectorAssembler(inputCols=numeric_cols, outputCol="corr_features")
df_corr = assembler.transform(df_labeled).select("corr_features")
corr_matrix = Correlation.corr(df_corr, "corr_features", "pearson").head()[0]
print(corr_matrix.toArray())
# Compute the correlation matrix between all numeric columns
# Essentially every value shows a correlation between two vectors
# Each vector is a numeric column
# If two correleations are close to 1, we remove one of the columns since it would be redundant
# All of the 1's form a diagonal, therefore there are no significant correlations
# All of the 1's come from a vector being compared to itself.

from pyspark.ml.feature import VectorAssembler, StandardScaler
from pyspark.ml.classification import RandomForestClassifier, LogisticRegression
from pyspark.ml.evaluation import MulticlassClassificationEvaluator

features = [c for c in numeric_cols if c != "popularity"]

assembler = VectorAssembler(
    inputCols=features,
    outputCol="features",
    handleInvalid="skip"
)

df_vec = assembler.transform(df_labeled).select("features", "label")

train, test = df_vec.randomSplit([0.8, 0.2], seed=42)

lr = LogisticRegression(
    labelCol="label",
    featuresCol="features",
    family="multinomial",
    maxIter=200,
    regParam=0.01,
    elasticNetParam=0.5
)

lr_model = lr.fit(train)
lr_pred  = lr_model.transform(test)

lr_model.write().overwrite().save(f"gs://{bucket}/out/mlmodel")
# lr_pred.write().overwrite().save(f"gs://{bucket}/output/mlpred")

evaluator = MulticlassClassificationEvaluator(
    labelCol="label", predictionCol="prediction", metricName="accuracy"
)

print("Accuracy:", evaluator.evaluate(lr_pred))